# Generated by Django 5.2.17 on 2026-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "нотатка",
                "verbose_name_plural": "нотатки",
            },
        ),
        migrations.AddField(
            model_name="note",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="Закріплена"),
        ),
    ]
