# Generated by Django 5.2.17 on 2026-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_app", "0002_alter_note_options_note_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Низький"),
                    (2, "Звичайний"),
                    (3, "Високий"),
                    (4, "Терміновий"),
                ],
                default=2,
                verbose_name="Пріоритет",
            ),
        ),
    ]
